---
- name: Install Java
  hosts: all
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: Install Java Default JRE
    apt:
      name: default-jre
      update_cache: yes

- name: Install Jenkins
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
  - name: wget
    ansible.builtin.shell:
      cmd: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
  - name: Download Jenkins repository
    ansible.builtin.shell:
      cmd: sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - name: Install Jenkins
    apt:
     name: jenkins
     update_cache: yes

- name: Install MySQL
  hosts: all
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: apt get mysql
    apt:
      name: mysql-client
      update_cache: yes

- name: Install Python
  hosts: all
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: Install Supporting Software
    apt:
      name: software-properties-common
      update_cache: yes
  - name: Add Deadsnakes repo
    ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
  - name: Install Python3
    apt:
      name: python3.8
      update_cache: yes

  - name: Install Python2
    apt:
      name: python2
      update_cache: yes
  - name: Download python2 script to install pip2
    get_url:
      url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
      dest: ~/get-pip.py
  - name: Run script to install pip2
    ansible.builtin.shell: 
      cmd: sudo python2.7 ~/get-pip.py
  - name: Install Python3 pip
    apt:
      name:  python3-pip
      update_cache: yes

- name: Install & Setup Ansible
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Add Ansible repository
    ansible.builtin.apt_repository:
      repo: ppa:ansible/ansible
  - name: Install Ansible
    apt: 
      name: ansible
      update_cache: yes
      
- name: Copy SSH key
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
  - name: copy key
    copy: 
      src: ~/.ssh/Roam.pem
      dest: /home/ubuntu/Roam.pem
  - name: Give permissions
    ansible.builtin.shell:
      cmd: sudo chmod 404 /home/ubuntu/Roam.pem

- name: Run SQL Script
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Install pymysql
    ansible.builtin.shell:
      cmd: python3 -m pip install PyMySQL
  - name: copy script to remote
    copy:
      src: ~/table_creation_and_inserts.sql
      dest: ~/table_creation_and_inserts.sql
  - name: Run SQL Script
    community.mysql.mysql_db: 
      state: import
      name: movie_db
      login_host: dbmysql.cx02uzagq3fl.us-west-1.rds.amazonaws.com
      login_user: dbadmin
      login_password: dbpass1234567!
      target: ~/table_creation_and_inserts.sql